name: Deploy to DEV (GitHub Pages)

on:
  push:
    branches:
      - develop

permissions:
  contents: write

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    environment:
      name: dev
      url: https://salonijain3112.github.io/expense-management/dev/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: corepack yarn install --immutable

      - name: Build project
        run: corepack yarn build

      - name: Deploy to gh-pages (dev folder)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          destination_dir: dev
          publish_branch: gh-pages
          keep_files: true
