name: Deploy to PROD (GitHub Pages)

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    environment:
      name: prod
      url: https://salonijain3112.github.io/expense-management/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug ref
        run: echo "Triggered by $GITHUB_REF"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: corepack yarn install --immutable

      - name: Build project
        env:
          BUILD_TARGET: prod
        run: corepack yarn build

      - name: Deploy to gh-pages (root)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/prod
          publish_branch: gh-pages
